/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SmartDevicesRouteImport } from './routes/smart-devices'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as PhonesRouteImport } from './routes/phones'
import { Route as LaptopsRouteImport } from './routes/laptops'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartDevicesRoute = SmartDevicesRouteImport.update({
  id: '/smart-devices',
  path: '/smart-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonesRoute = PhonesRouteImport.update({
  id: '/phones',
  path: '/phones',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsRoute = LaptopsRouteImport.update({
  id: '/laptops',
  path: '/laptops',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/laptops': typeof LaptopsRoute
  '/phones': typeof PhonesRoute
  '/repairs': typeof RepairsRoute
  '/smart-devices': typeof SmartDevicesRoute
  '/training': typeof TrainingRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/laptops': typeof LaptopsRoute
  '/phones': typeof PhonesRoute
  '/repairs': typeof RepairsRoute
  '/smart-devices': typeof SmartDevicesRoute
  '/training': typeof TrainingRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/laptops': typeof LaptopsRoute
  '/phones': typeof PhonesRoute
  '/repairs': typeof RepairsRoute
  '/smart-devices': typeof SmartDevicesRoute
  '/training': typeof TrainingRoute
  '/trust': typeof TrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/laptops'
    | '/phones'
    | '/repairs'
    | '/smart-devices'
    | '/training'
    | '/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/laptops'
    | '/phones'
    | '/repairs'
    | '/smart-devices'
    | '/training'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/laptops'
    | '/phones'
    | '/repairs'
    | '/smart-devices'
    | '/training'
    | '/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LaptopsRoute: typeof LaptopsRoute
  PhonesRoute: typeof PhonesRoute
  RepairsRoute: typeof RepairsRoute
  SmartDevicesRoute: typeof SmartDevicesRoute
  TrainingRoute: typeof TrainingRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-devices': {
      id: '/smart-devices'
      path: '/smart-devices'
      fullPath: '/smart-devices'
      preLoaderRoute: typeof SmartDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phones': {
      id: '/phones'
      path: '/phones'
      fullPath: '/phones'
      preLoaderRoute: typeof PhonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops': {
      id: '/laptops'
      path: '/laptops'
      fullPath: '/laptops'
      preLoaderRoute: typeof LaptopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LaptopsRoute: LaptopsRoute,
  PhonesRoute: PhonesRoute,
  RepairsRoute: RepairsRoute,
  SmartDevicesRoute: SmartDevicesRoute,
  TrainingRoute: TrainingRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
